### ISSUE TITLE
FunctionClauseError when making request

### ISSUE THREAD

**Issue by nskalis** [elixir-mint/mint#266]
Hi,

Given that this is my first exercise in Elixir and since I am newish to gRPC, I would greatly appreciate your help and advice.

### Adding some context

I would like to consume a 3rd party gRPC server, in my case it is a high-end router, actually there are many of those running different versions of gRPC servers, but I'll use a simple example (details below) to demonstrate my issue/question.

In such a scenario, I am ok avoiding gRPC stubs and dealing only with (de)serialising messages. Better to declare an endpoint and a body than producing and using code for it.

_I would like to use Mint as a gRPC client._

### What the docs say about protobuf

Based on https://github.com/tony612/protobuf-elixir/blob/master/lib/protobuf/json.ex
I would like to decode protobuf encoded messages to `json`

### What the docs say about gRPC

Based on https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md
it is doable to use a HTTP2 client if you specify the `Content-Type` (to be `application/grpc`) and a 5 byte header in each request:

1. `Length-Prefixed-Message` (use `0x00` for `Compressed-Flag`)
2. `Message-Length`

### Running a gRPC server as an example

I tried to find a playground/public gRPC server, but no luck, so I am using the introductory example in the official page of gRPC https://grpc.io/docs/languages/go/quickstart/, please see below for guidelines how you can replicate the examples (it is a few commands away)
```
$ go run greeter_server/main.go  # from one terminal
```

### Running a gRPC client (grpcurl) as a method to verify

```
$ wget https://github.com/fullstorydev/grpcurl/releases/download/v1.6.1/grpcurl_1.6.1_linux_x86_64.tar.gz
$ cp grpcurl_1.6.1_linux_x86_64/grpcurl /usr/local/sbin/

$ cd grpc-go/examples/helloworld
$ grpcurl -import-path ./helloworld -proto helloworld.proto list
$ grpcurl -import-path ./helloworld -proto helloworld.proto describe helloworld.Greeter
$ grpcurl -plaintext -import-path ./helloworld -proto helloworld.proto   127.0.0.1:50051 helloworld.Greeter/SayHello 
{
  "message": "Hello "
}
$ grpcurl -plaintext -import-path ./helloworld -proto helloworld.proto  -d '{"name":"Niko"}' 127.0.0.1:50051 helloworld.Greeter/SayHelloAgain 
{
  "message": "Hello again Niko"
}
```

### Making the gRPC calll (using Mint)

```
iex(3)> {:ok, conn} = Mint.HTTP2.connect(:http, "127.0.0.1", 50051) 
{:ok,
 %Mint.HTTP2{
   buffer: "",
   client_settings: %{
     enable_push: true,
     max_concurrent_streams: 100,
     max_frame_size: 16384
   },
   client_settings_queue: {[[]], []},
   decode_table: %Mint.HTTP2.HPACK.Table{
     entries: [],
     length: 0,
     max_table_size: 4096,
     size: 0
   },
   encode_table: %Mint.HTTP2.HPACK.Table{ 
     entries: [],
     length: 0,
     max_table_size: 4096,
     size: 0
   },
   headers_being_processed: nil,
   hostname: "127.0.0.1",
   mode: :active,
   next_stream_id: 3,
   open_client_stream_count: 0,
   open_server_stream_count: 0,
   ping_queue: {[], []},
   port: 50051,
   private: %{},
   ref_to_stream_id: %{}, 
   scheme: "http",
   server_settings: %{
     enable_push: true,
     initial_window_size: 65535,
     max_concurrent_streams: 100,
     max_frame_size: 16384,
     max_header_list_size: :infinity
   },
   socket: #Port<0.774>,
   state: :open,
   streams: %{},
   transport: Mint.Core.Transport.TCP,
   window_size: 65535
 }}
```
```
iex(6)> {:ok, conn, request_ref} = Mint.HTTP2.request(conn, "GET", "helloworld.Greeter/SayHello", _headers = [{"content-type", "application/grpc"}, {"length-prefixed-message", 0x00}, {"message-length", 0x00}], nil) 
** (FunctionClauseError) no function clause matching in Mint.HTTP2.HPACK.encode_headers/3    
    
    The following arguments were given to Mint.HTTP2.HPACK.encode_headers/3:
    
        # 1
        [
          {:store_name, "length-prefixed-message", 0},
          {:store_name, "message-length", 0}
        ]
    
        # 2
        %Mint.HTTP2.HPACK.Table{entries: [], length: 0, max_table_size: 4096, size: 0}
    
        # 3
        [
          [
            [
              [[[[], <<130>>], [<<4>>, ["\e", "helloworld.Greeter/SayHello"]]], <<134>>],
              [<<1>>, [<<15>>, "127.0.0.1:50051"]]
            ],
            [<<15, 43>>, ["\n", "mint/1.1.0"]]
          ],
          [<<15, 16>>, [<<16>>, "application/grpc"]]
        ]
    
    Attempted function clauses (showing 2 out of 2):
    
        defp encode_headers([], table, acc)
        defp encode_headers([{action, name, value} | rest], table, acc) when (action === :store or (action === :store_name or (action === :no_store or action === :never_store))) and is_binary(name) and is_binary(value)
    
    (mint 1.1.0) lib/mint/http2/hpack.ex:186: Mint.HTTP2.HPACK.encode_headers/3
    (elixir 1.10.4) lib/map.ex:878: Map.get_and_update!/3
    (mint 1.1.0) lib/mint/http2.ex:1132: Mint.HTTP2.encode_headers/4
    (mint 1.1.0) lib/mint/http2.ex:503: Mint.HTTP2.request/5
```

_Would you be so kind to advise what I am doing wrong?_

##### Installing Go

```
$ wget https://golang.org/doc/install?download=go1.14.6.linux-amd64.tar.gz
$ tar -C /usr/local -xzf go1.14.6.linux-amd64.tar.gz
$ export PATH=$PATH:/usr/local/go/bin
```

##### Installing protoc

```
$ wget https://github.com/protocolbuffers/protobuf/releases/download/v3.12.3/protoc-3.12.3-linux-x86_64.zip
```

##### Installing Go plugin

```
$ export GO111MODULE=on
$ go get github.com/golang/protobuf/protoc-gen-go
```

##### Downloading example gRPC server/client

```
$ git clone -b v1.30.0 https://github.com/grpc/grpc-go
```

##### Running the example 

```
$ cd grpc-go/examples/helloworld
$ go run greeter_server/main.go  # from one terminal
$ go run greeter_client/main.go  # from another terminal
```

##### Updating the example (proto)

As described in https://grpc.io/docs/languages/go/quickstart/#update-a-grpc-service

##### Updating the example (mechanics)

```
$ cd grpc-go/examples/helloworld
$ cd ../../cmd/protoc-gen-go-grpc && go install .
$ ~/protoc-3/bin/protoc --go_out=Mgrpc/service_config/service_config.proto=/internal/proto/grpc_service_config:. --go-grpc_out=Mgrpc/service_config/service_config.proto=/internal/proto/grpc_service_config:. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative helloworld/helloworld.proto
```

##### Updating the example (source code)

As described in https://grpc.io/docs/languages/go/quickstart/#update-and-run-the-application

**Comment by whatyouhide** [comment]
@nskalis there is a problem with this call:

```elixir
{:ok, conn, request_ref} = Mint.HTTP2.request(conn, "GET", "helloworld.Greeter/SayHello", _headers = [{"content-type", "application/grpc"}, {"length-prefixed-message", 0x00}, {"message-length", 0x00}], nil)
```

You are using integer values as header values, but header values need to be binaries. I think that's what's going on. Try with

```elixir
{:ok, conn, request_ref} = Mint.HTTP2.request(conn, "GET", "helloworld.Greeter/SayHello", _headers = [{"content-type", "application/grpc"}, {"length-prefixed-message", <<0x00>>}, {"message-length", <<0x00>>}], nil)
```

Does that work?

**Comment by nskalis** [comment]
thanks @whatyouhide for looking into it

```
iex(2)> {:ok, conn, request_ref} = Mint.HTTP2.request(conn, "GET", "helloworld.Greeter/SayHello", _headers = [{"content-type", "application/grpc"}, {"length-prefixed-message", <<0x00>>}, {"message-length", <<0x00>>}], nil)
{:ok,
 %Mint.HTTP2{
   buffer: "",
   client_settings: %{
     enable_push: true,
     max_concurrent_streams: 100,
     max_frame_size: 16384
   },
   client_settings_queue: {[[]], []},
   decode_table: %Mint.HTTP2.HPACK.Table{
     entries: [],
     length: 0,
     max_table_size: 4096,
     size: 0
   },
   encode_table: %Mint.HTTP2.HPACK.Table{ 
     entries: [{"message-length", <<0>>}, {"length-prefixed-message", <<0>>}],
     length: 2,
     max_table_size: 4096,
     size: 103
   },
   headers_being_processed: nil,
   hostname: "127.0.0.1",
   mode: :active,
   next_stream_id: 5,
   open_client_stream_count: 1,
   open_server_stream_count: 0,
   ping_queue: {[], []},
   port: 50051,
   private: %{},
   ref_to_stream_id: %{#Reference<0.2884225548.853540870.220602> => 3},
   scheme: "http",
   server_settings: %{
     enable_push: true,
     initial_window_size: 65535,
     max_concurrent_streams: 100,
     max_frame_size: 16384,
     max_header_list_size: :infinity
   },
   socket: #Port<0.6>,
   state: :open,
   streams: %{
     3 => %{
       id: 3,
       received_first_headers?: false,
       ref: #Reference<0.2884225548.853540870.220602>,
       state: :half_closed_local,
       window_size: 65535
     }
   },
   transport: Mint.Core.Transport.TCP,
   window_size: 65535
 }, #Reference<0.2884225548.853540870.220602>}
```
```
iex(3)> flush()
{:tcp, #Port<0.6>, <<0, 0, 0, 4, 1, 0, 0, 0, 0>>}
:ok
```
this is for sure not a `Hello `, and it is not a `utf-8` encoded string either. 

Would you be so kind to advise further?

**Comment by whatyouhide** [comment]
You need to use `Mint.HTTP.stream/2` on the received message in order to parse it.

```elixir
msg = receive do: msg -> msg end
Mint.HTTP.stream(conn, msg)
```

I don't think there's any bug with Mint here so I'll close the issue for now but feel free to keep commenting if you're still having issues :)

**Comment by nskalis** [comment]
After a more careful look into this, what https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md says about `Length-Prefixed-Message` is that it is IN the data itself.

Assuming a request with an empty body and no compression

- Compressed-Flag = 0 (1 byte)
- Message-Length = 0 (4 byte unsigned integer)
- Message = ?

Would you be so kind to advise on the following two questions: 
(since you have implemented it and you have more domain expertise that I do)

1. if there is no body, should be the message be the `NULL` byte?
2. is `EOS (end-of-stream)` automatically appended at the end of the request (based on the above link/specification it should be, but I don't know if I have to do that explicitly)

Right now, I can make a request (successfully?), I see the server receiving that at least, like this
```
iex(108)> len = 0
0
iex(109)> {:ok, conn, request_ref} = Mint.HTTP2.request(conn, "POST", "helloworld.Greeter/SayHello", _headers = [{"content-type", "application/grpc"}], IO.iodata_to_binary([<<0::unsigned-integer-size(8)-big>>, <<len::unsigned-integer-size(32)-big>>, <<0>>]))
{:ok,
 %Mint.HTTP2{
   buffer: "",
   client_settings: %{
     enable_push: true,
     max_concurrent_streams: 100,
     max_frame_size: 16384
   },
   client_settings_queue: {[[]], []},
   decode_table: %Mint.HTTP2.HPACK.Table{
     entries: [],
     length: 0,
     max_table_size: 4096,
     size: 0
   },
   encode_table: %Mint.HTTP2.HPACK.Table{ 
     entries: [],
     length: 0,
     max_table_size: 4096,
     size: 0
   },
   headers_being_processed: nil,
   hostname: "127.0.0.1",
   mode: :active,
   next_stream_id: 11,
   open_client_stream_count: 4,
   open_server_stream_count: 0,
   ping_queue: {[], []},
   port: 50051,
   private: %{},
   ref_to_stream_id: %{
     #Reference<0.2134901607.1396178947.23585> => 3,
     #Reference<0.2134901607.1396178947.23664> => 5,
     #Reference<0.2134901607.1396178947.23690> => 7,
     #Reference<0.2134901607.1396178947.23773> => 9
   },
   scheme: "http",
   server_settings: %{
     enable_push: true,
     initial_window_size: 65535,
     max_concurrent_streams: 100,
     max_frame_size: 16384,
     max_header_list_size: :infinity
   },
   socket: #Port<0.817>,
   state: :open,
   streams: %{
     3 => %{
       id: 3,
       received_first_headers?: false,
       ref: #Reference<0.2134901607.1396178947.23585>,
       state: :half_closed_local,
       window_size: 65529
     },
     5 => %{
       id: 5,
       received_first_headers?: false,
       ref: #Reference<0.2134901607.1396178947.23664>,
       state: :half_closed_local,
       window_size: 65529
     },
     7 => %{
       id: 7,
       received_first_headers?: false,
       ref: #Reference<0.2134901607.1396178947.23690>,
       state: :half_closed_local,
       window_size: 65529
     },
     9 => %{
       id: 9,
       received_first_headers?: false,
       ref: #Reference<0.2134901607.1396178947.23773>,
       state: :half_closed_local,
       window_size: 65529
     }
   },
   transport: Mint.Core.Transport.TCP,
   window_size: 65511
 }, #Reference<0.2134901607.1396178947.23773>}
```

But, 
```
iex(110)> next_message =
...(110)>   receive do
...(110)>     msg -> msg
...(110)>   end
{:tcp, #Port<0.817>, <<0, 0, 0, 4, 1, 0, 0, 0, 0>>}
iex(111)> {:ok, conn, responses} = Mint.HTTP2.stream(conn, next_message)
{:ok,
 %Mint.HTTP2{
   buffer: "",
   client_settings: %{
     enable_push: true,
     max_concurrent_streams: 100,
     max_frame_size: 16384
   },
   client_settings_queue: {[], []},
   decode_table: %Mint.HTTP2.HPACK.Table{
     entries: [],
     length: 0,
     max_table_size: 4096,
     size: 0
   },
   encode_table: %Mint.HTTP2.HPACK.Table{
     entries: [],
     length: 0,
     max_table_size: 4096,
     size: 0
   },
   headers_being_processed: nil,
   hostname: "127.0.0.1",
   mode: :active,
   next_stream_id: 11,
   open_client_stream_count: 4,
   open_server_stream_count: 0,
   ping_queue: {[], []},
   port: 50051,
   private: %{},
   ref_to_stream_id: %{
     #Reference<0.2134901607.1396178947.23585> => 3,
     #Reference<0.2134901607.1396178947.23664> => 5,
     #Reference<0.2134901607.1396178947.23690> => 7,
     #Reference<0.2134901607.1396178947.23773> => 9
   },
   scheme: "http",
   server_settings: %{
     enable_push: true,
     initial_window_size: 65535,
     max_concurrent_streams: 100,
     max_frame_size: 16384,
     max_header_list_size: :infinity
   },
   socket: #Port<0.817>,
   state: :open,
   streams: %{
     3 => %{
       id: 3,
       received_first_headers?: false,
       ref: #Reference<0.2134901607.1396178947.23585>,
       state: :half_closed_local,
       window_size: 65529
     },
     5 => %{
       id: 5,
       received_first_headers?: false,
       ref: #Reference<0.2134901607.1396178947.23664>,
       state: :half_closed_local,
       window_size: 65529
     },
     7 => %{
       id: 7,
       received_first_headers?: false,
       ref: #Reference<0.2134901607.1396178947.23690>,
       state: :half_closed_local,
       window_size: 65529
     },
     9 => %{
       id: 9,
       received_first_headers?: false,
       ref: #Reference<0.2134901607.1396178947.23773>,
       state: :half_closed_local,
       window_size: 65529
     }
   },
   transport: Mint.Core.Transport.TCP,
   window_size: 65511
 }, []}
iex(112)> responses
[]
```

Ideally, I should receive a response that I would decode to 
```
{
  "message": "Hello "
}
```

I don't know how to troubleshoot this further. Can you please help out?

**Comment by nskalis** [comment]
@whatyouhide I would greatly appreciate your help and advice in having a `hello world` request/response over HTTP2  working. 

On purpose, I have omitted the non-relevant (to Mint) protocol buffers encoding part from the example provided, as I am not receiving a response yet from the HTTP2 (gRPC) server.

Your domain expertise and the official docs (see link above) would help shed light about why there is no response.

I am not sure if other maintainers of this library have the time to look into this and can help. Please feel free to involve any.

From my side, you can have all the support you guys will need with testing, feedback, etc.

**Comment by nskalis** [comment]
changing the `content-type` to `application/grpc+proto` yields a result
(I read that this is necessary to associate the service with HTTP/2 when the interface of gRPC is defined based on protobuf)

```
iex(16)> {:ok, conn, request_ref} = Mint.HTTP2.request(conn, "POST", "helloworld.Greeter/SayHello", _headers = [{"content-type", "application/grpc+proto"}], body)
{:ok,
 %Mint.HTTP2{
   buffer: "",
   client_settings: %{
     enable_push: true,
     max_concurrent_streams: 100,
     max_frame_size: 16384
   },
   client_settings_queue: {[[]], []},
   decode_table: %Mint.HTTP2.HPACK.Table{
     entries: [],
     length: 0,
     max_table_size: 4096,
     size: 0
   },
   encode_table: %Mint.HTTP2.HPACK.Table{ 
     entries: [],
     length: 0,
     max_table_size: 4096,
     size: 0
   },
   headers_being_processed: nil,
   hostname: "127.0.0.1",
   mode: :active,
   next_stream_id: 5,
   open_client_stream_count: 1,
   open_server_stream_count: 0,
   ping_queue: {[], []},
   port: 50051,
   private: %{},
   ref_to_stream_id: %{#Reference<0.1203570531.1862533126.203492> => 3},
   scheme: "http",
   server_settings: %{
     enable_push: true,
     initial_window_size: 65535,
     max_concurrent_streams: 100,
     max_frame_size: 16384,
     max_header_list_size: :infinity
   },
   socket: #Port<0.7>,
   state: :open,
   streams: %{
     3 => %{
       id: 3,
       received_first_headers?: false,
       ref: #Reference<0.1203570531.1862533126.203492>,
       state: :half_closed_local,
       window_size: 65530
     }
   },
   transport: Mint.Core.Transport.TCP,
   window_size: 65530
 }, #Reference<0.1203570531.1862533126.203492>}
```
```
iex(18)> next_message =
...(18)>   receive do
...(18)>     msg -> msg
...(18)>   end
{:tcp, #Port<0.6>,
 <<0, 0, 4, 8, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 8, 6, 0, 0, 0, 0, 0, 2, 4, 16,
   16, 9, 14, 7, 7, 0, 0, 14, 1, 4, 0, 0, 0, 3, 136, 95, 139, 29, 117, 208, 98,
   13, ...>>}
```

**Comment by ericmj** [comment]
Like @whatyouhide said:

> You need to use Mint.HTTP.stream/2 on the received message in order to parse it.

See his message from earlier: https://github.com/elixir-mint/mint/issues/266#issuecomment-661044689.

For more information please see the usage examples in the README: https://github.com/elixir-mint/mint#usage.

**Comment by nskalis** [comment]
thanks @ericmj for looking into it, when I stream it:
```
iex(21)> {:ok, conn, responses} = Mint.HTTP2.stream(conn, next_message)
** (MatchError) no match of right hand side value: :unknown
```

I was not sure about unary vs. client streaming (and if `Mint.HTTP.stream/2` is related) since gRPC usually has four modes, unary, client streaming, server streaming and bidirectional streaming. 

Re-opening the issue to figure out the `MatchError` because of `unknown`, any ideas?

**Comment by nskalis** [comment]
you're right so this is what I found out:

in gRPC what is commonly talked about is service/method, without the leading slash
but in HTTP it has the leading slash since it is a path

that was the problem.

Now, you guys also know how to make a gRPC request using Mint ;)

**Comment by ericmj** [comment]
Looking at the `stream/2` docs https://hexdocs.pm/mint/Mint.HTTP.html#stream/2 it says:

> If the given message is not from the connection's socket, this function returns :unknown.

So you are passing in a message that does not relate to the mint connection.
