### ISSUE TITLE
Unexpected unwrapped return `%Mint.TransportError{reason: :closed}` from `Mint.HTTP1.connect/4`

### ISSUE THREAD

**Issue by jozuas** [elixir-mint/mint#438]
- Req version: 0.5.1
- Finch version: 0.18.0
- Mint version: 1.6.1
- Elixir version: 1.15.7
- OTP version: Erlang/OTP 26 [erts-14.2.5]

I observed the following in my application logs:
```
** (CaseClauseError) no case clause matching: %Mint.TransportError{reason: :closed}
(finch 0.18.0) lib/finch/http1/conn.ex:52: Finch.HTTP1.Conn.connect/2
(finch 0.18.0) lib/finch/http1/pool.ex:58: anonymous fn/10 in Finch.HTTP1.Pool.request/6
(nimble_pool 1.1.0) lib/nimble_pool.ex:462: NimblePool.checkout!/4
(finch 0.18.0) lib/finch/http1/pool.ex:52: Finch.HTTP1.Pool.request/6
(finch 0.18.0) lib/finch.ex:472: anonymous fn/4 in Finch.request/3
(telemetry 1.2.1) /opt/terrapin-app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
(req 0.5.1) lib/req/steps.ex:977: Req.Steps.run_finch_request/3
(req 0.5.1) lib/req/steps.ex:809: Req.Steps.run_finch/4
```

[lib/finch/http1/conn.ex:52](https://github.com/sneako/finch/blob/49433a1a28e8b54a45860e78de18cde3283e9953/lib/finch/http1/conn.ex#L52-L62):
```elixir
    case Mint.HTTP.connect(conn.scheme, conn.host, conn.port, conn_opts) do
      {:ok, mint} ->
        Telemetry.stop(:connect, start_time, meta)
        SSL.maybe_log_secrets(conn.scheme, conn_opts, mint)
        {:ok, %{conn | mint: mint}}

      {:error, error} ->
        meta = Map.put(meta, :error, error)
        Telemetry.stop(:connect, start_time, meta)
        {:error, conn, error}
    end
```

[Mint.HTTP1.connect/4 return type should be](https://github.com/elixir-mint/mint/blob/d3070089d4d22e8062e94df1334889437658fdee/lib/mint/http1.ex#L128-L129):
```elixir
  @spec connect(Types.scheme(), Types.address(), :inet.port_number(), keyword()) ::
          {:ok, t()} | {:error, Types.error()}
```

Not sure how to replicate given that this for me is a transient issue

**Comment by wojtekmach** [comment]
seems like a Finch bug, could you move this issue to Finch repo?

**Comment by jozuas** [comment]
Looking at my logs I've also discovered another unexpected unwrapped return type from `Min.HTTP1.connect/4`:

```elixir
** (CaseClauseError) no case clause matching: %Mint.TransportError{reason: %Mint.TransportError{reason: :timeout}}
(finch 0.18.0) lib/finch/http1/conn.ex:52: Finch.HTTP1.Conn.connect/2
(finch 0.18.0) lib/finch/http1/pool.ex:58: anonymous fn/10 in Finch.HTTP1.Pool.request/6
(nimble_pool 1.1.0) lib/nimble_pool.ex:462: NimblePool.checkout!/4
(finch 0.18.0) lib/finch/http1/pool.ex:52: Finch.HTTP1.Pool.request/6
(finch 0.18.0) lib/finch.ex:472: anonymous fn/4 in Finch.request/3
(telemetry 1.2.1) /opt/terrapin-app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
(req 0.5.0) lib/req/steps.ex:953: Req.Steps.run_finch_request/3
(req 0.5.0) lib/req/steps.ex:785: Req.Steps.run_finch/4
```

**Comment by jozuas** [comment]
> Can you share which URL you hit? Is it over http or https? ipv4, ipv6? Any extra context would really help.

I am making `Req` requests through a pool of proxies.

It looks roughly like:
```elixir
  @spec base_req() :: Req.Request.t()
  def base_req() do
    proxy = Tp.Proxy.rotate()

    Req.new(
      base_url: "https://...",
      connect_options: [
        proxy: {:http, proxy.ip, proxy.port, []},
        proxy_headers: [{"Proxy-Authorization", "Basic: #{Base.encode64(proxy.userpass)}"}]
      ]
    )
  end
```

We have around 10 proxies. They are quite unreliable. We get intermittent HTTP 407, `:timeout`, `:ehostunreach`, etc. from the proxies.

**Comment by whatyouhide** [comment]
> `%Mint.TransportError{reason: %Mint.TransportError{reason: :timeout}}`

This is definitely an error yeah. I'll try to take a look.

**Comment by jozuas** [comment]
@whatyouhide any updates 🙂?

**Comment by jozuas** [comment]
I think I will:
1. Fork the project
2. Add some extra diagnostics
3. Run in prod, and see what information I can capture

Let's see what turns up.

**Comment by whatyouhide** [comment]
@jozuas sounds fantastic, thank you.

**Comment by jozuas** [comment]
I'm looking at my AppSignal error tracker, and I see that the last time I had an exception for this was 17 days ago, it's probably faster to look at the code 😅

**Comment by jozuas** [comment]
Ah, well, here we go:

Follow `upgrade_connection/3`:
https://github.com/elixir-mint/mint/blob/63ce63c3a28db6832e6f39a7069193a5c3e53fc0/lib/mint/tunnel_proxy.ex#L8-L14

Follow `wrap_in_proxy_error/1`:
https://github.com/elixir-mint/mint/blob/63ce63c3a28db6832e6f39a7069193a5c3e53fc0/lib/mint/tunnel_proxy.ex#L39-L52

https://github.com/elixir-mint/mint/blob/63ce63c3a28db6832e6f39a7069193a5c3e53fc0/lib/mint/tunnel_proxy.ex#L119-L129

And so the real return of `upgrade_connection/3` is:
```
{:ok, ...} | %HTTPError{}
```

Instead of 
```
{:ok, ...} | {:error, %HTTPError{}}
```
